apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3TmpReU5UQXhNREFlRncweU1ERXhNall5TVRFd01UQmFGdzB6TURFeE1qUXlNVEV3TVRCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3TmpReU5UQXhNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkNnZHoxS0JyenNrRDZ4MmFLMjV0dk9YVTRINGhTc09sMnc4aEk3QjdtK3UKckQ5ckRUZHhKWXlad3FDM1cvVGV3clE4S2pjeVl1eUVpNGpCZEdvM3lTQ2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUY3dnNqYXY0eXo1CnJycmpPMVVtN1lrSlZVVUx1YXpnSlZSaEVXdG5pRVF4QWlFQWk4ZzFWWjVKd0RnVDJOL25Ib3YxNnFoVEorRlIKQkxwdUpXRlJBaU02dWRjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://master1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: f8ed93bedcea9a33ffc7367c229ef263
    username: admin