apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3TmpReU5ERTNPVEFlRncweU1ERXhNall5TURVMk1UbGFGdzB6TURFeE1qUXlNRFUyTVRsYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3TmpReU5ERTNPVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkdHM1N2MUZpWExKWGY1SktYSW1XTUExV0s1dW1taHpWUnR3elNBVER3cU4KUjFsM2gzMVZiNlBJNU0zc3hicmxpbUdIREJ5VzRaQUh5V0MzU0Z0Rzl6ZWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURLOTA5Q3JyYUpyCklLQzFPcjJ5NVpvY1ZEb3JZSUQ2NVRVb1NBOGQzRzljQWlCZkNUNnl1ZkVpWlllbEtaQmxNek5jcWlkT2J3S3gKc1JxaUlHSDBmQUZqSHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://master1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 6657994d683ff1a0bbedd6929243b1a0
    username: admin