apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
    release: istio
  name: kiali-np
  namespace: istio-system
spec:
  ports:
  - name: http-kiali-np
    port: 20001
    protocol: TCP
    targetPort: 20001
    nodePort: 30002
  selector:
    app: kiali
  sessionAffinity: None
  type: NodePort
